job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small maven hosted on github")
    scm {
        git('https://github.com/MichaelSsSs88/pet-clinic.git', 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
            maven{
                mavenInstallation('3.9.3')
                maven('verify')
                maven('clean package', 'First-Maven-Project-Via-DSL/pom.xml')
                maven('clean package', 'First-Maven-Project-Via-DSL/pet-clinic-data/pom.xml')
                maven('clean package', 'First-Maven-Project-Via-DSL/pet-clinic-web/pom.xml' )
            }

        }
        publishers {
            archiveArtifacts '**/*.war,**/*.jar'
        }
}
